spring.application.name=gamesapi
spring.datasource.url=jdbc:mysql://localhost:3306/gamesapi
spring.datasource.username=root
spring.datasource.password=naruto2527
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true